import type { Character } from '@/api/validation'

export const mockCharacters: Character[] = [
  {
    id: 1,
    firstName: 'Eddard',
    lastName: 'Stark',
    fullName: 'Eddard Stark',
    title: 'Lord of Winterfell',
    family: 'House Stark',
    image: 'eddard-stark.jpg',
    imageUrl: 'https://thronesapi.com/assets/images/eddard-stark.jpg',
  },
  {
    id: 2,
    firstName: 'Sansa',
    lastName: 'Stark',
    fullName: 'Sansa Stark',
    title: 'Princess',
    family: 'House Stark',
    image: 'sansa-stark.jpg',
    imageUrl: 'https://thronesapi.com/assets/images/sansa-stark.jpg',
  },
  {
    id: 3,
    firstName: 'Daenerys',
    lastName: 'Targaryen',
    fullName: 'Daenerys Targaryen',
    title: 'Mother of Dragons',
    family: 'House Targaryen',
    image: 'daenerys.jpg',
    imageUrl: 'https://thronesapi.com/assets/images/daenerys.jpg',
  },
  {
    id: 4,
    firstName: 'Cersei',
    lastName: 'Lannister',
    fullName: 'Cersei Lannister',
    title: 'Queen of the Seven Kingdoms',
    family: 'House Lannister',
    image: 'cersei-lannister.jpg',
    imageUrl: 'https://thronesapi.com/assets/images/cersei-lannister.jpg',
  },
  {
    id: 5,
    firstName: 'Jon',
    lastName: 'Snow',
    fullName: 'Jon Snow',
    title: 'King in the North',
    family: 'House Stark',
    image: 'jon-snow.jpg',
    imageUrl: 'https://thronesapi.com/assets/images/jon-snow.jpg',
  },
]
